production:
    adapter: mysql2
    encoding: utf8
    database: designunited
    username: dvprooijen
    password: ja2deiK5

development:
    adapter: mysql2
    encoding: utf8
    database: designunited
    username: dvprooijen
    password: ja2deiK5

