# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

About.create(:title => "DU: Platform", :content=>"<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam semper tortor ut mauris iaculis tempor tincidunt neque porttitor. Cras rutrum dapibus elementum. Ut pharetra blandit varius. Proin ac mauris augue. Donec lobortis quam in ante blandit iaculis consequat ipsum accumsan. Sed at nulla nec ligula pharetra tempus ut et nunc. Mauris vulputate sagittis lorem. Vestibulum fringilla, dolor eget imperdiet fermentum, mi tortor sagittis nunc, quis vehicula turpis nibh scelerisque diam. In vulputate aliquam sem, in pellentesque nibh ullamcorper et.</p><img src='http://t2.gstatic.com/images?q=tbn:ANd9GcQp6LrJKwIScJQvQMKDzEr1YOnNSHSeG8xJ5cLZArl_2mJA0d-Wog' width='300'/ style='float: left;'><p>Ut pharetra feugiat condimentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nullam nec elit risus. Cras augue mauris, eleifend vel dignissim vel, congue non nisl. Praesent facilisis fermentum erat, eu dapibus erat ultricies vitae. Curabitur ante nibh, hendrerit id gravida sed, pulvinar quis erat. Vestibulum sed sem vitae enim mattis luctus. Ut ornare justo et justo vulputate vel posuere nulla mattis. In hac habitasse platea dictumst. Curabitur sit amet orci felis. Aliquam vel diam ipsum, ac placerat enim. Nam id velit nulla, at laoreet mi. Nulla vestibulum ultricies volutpat. Nam sed nisl ac lectus fermentum suscipit. Cras ut nisi ipsum, eget condimentum ipsum. Aliquam erat volutpat.</p>", :published => true)
Profile.create(:firstname => "David", :middlename => "van", :lastname => "Prooijen", :suffix => "MSc", :university => "TU D")
Profile.create(:firstname => "Vikko", :lastname => "Smit", :suffix => "Ing.", :university => "TU D")